Repository intel/p3-analysis-library, pull requests merged in 2024-04, with the labels that each got.

#32 CI and pre-commit alignment
  .bandit
  .github/workflows/build-unittest.yml
  .github/workflows/lint-format.yml
  .github/workflows/run-precommit.yml
  .pre-commit-config.yaml
  p3/report/_snapshot.py
  pyproject.toml
Labels: bug

#33 Disabling pre-commit run on `main`
  .github/workflows/run-precommit.yml
Labels: bug

#35 Update GitHub templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#36 Move matplotlib code into to the backend
  p3/plot/_cascade.py
  p3/plot/_navchart.py
  p3/plot/backend/matplotlib.py
Labels: enhancement

#31 Update coverage schema to 0.3.0
  MANIFEST.in
  p3/data/_validation.py
  p3/data/coverage-0.3.0.schema
  p3/metrics/_divergence.py
  tests/data/test_validation.py
  tests/metrics/test_divergence.py
Labels: enhancement

#44 Simplify divergence usage by making cov optional
  p3/metrics/_divergence.py
  p3/report/_snapshot.py
Labels: documentation, enhancement

#45 Raise exception if # applications > # markers
  p3/plot/backend/matplotlib.py
Labels: bug

#40 Raise exception for cascades with > 26 platforms
  p3/plot/backend/matplotlib.py
Labels: bug
